service: sqs-check

frameworkVersion: '3'

provider:
  name: aws
  runtime: ruby2.7
  region: ap-northeast-1
configValidationMode: error
resources:
  Resources:
    MyQueue:
      Type: AWS::SQS::Queue
      Properties:
        QueueName: my-queue
functions:
  hello:
    handler: handler.hello
    architecture: arm64
    memorySize: 128
    timeout: 10
    events:
      - sqs:
          arn:
            Fn::GetAtt:
              - MyQueue
              - Arn
