service: sqs-check

frameworkVersion: '3'

plugins:
  - serverless-lift
provider:
  name: aws
  runtime: ruby2.7
  region: ap-northeast-1
configValidationMode: error

constructs:
  my-queue2:
    type: queue
    worker:
      architecture: arm64
      memorySize: 128
      timeout: 10
      handler: handler.hello
